export const PREF_UPDATE_FREQ = "update-frequency";
export const PREF_FOLLOWED_ONLY = "followed-only";
export const PREF_COMPACT_MODE = "compact-mode";
export const PREF_POSITION_TOPBAR = "position-in-topbar";
export const PREF_SHOW_NEXT_GAMES = "show-next-games";

export const PREF_LEAGUES = {
  Bund: "bund-enabled",
  Bund2: "bund2-enabled",
  UCL: "ucl-enabled",
  "English League Championship": "elc-enabled",
  "English League One": "l1-enabled",
  EPL: "epl-enabled",
  ISR: "isr-enabled",
  LaLiga: "laliga-enabled",
  LaLigaMX: "laligamx-enabled",
  "Ligue 1": "ligue1-enabled",
  MLS: "mls-enabled",
  "Serie A": "seriea-enabled",
};

export const DISPLAY_NAME = {
  Bund: "1. Bundesliga",
  Bund2: "2. Bundesliga",
  UCL: "UEFA Champions League",
  "English League Championship": "English League Championship",
  "English League One": "English League One",
  EPL: "Premier League",
  ISR: "Israeli Premier League (ISR)",
  LaLiga: "LaLiga",
  LaLigaMX: "La Liga MX",
  "Ligue 1": "Ligue 1",
  MLS: "MLS",
  "Serie A": "Serie A",
};

export const PREF_TOURNAMENTS = {
  "CONCACAF Gold Cup": "concacafgold-enabled",
  "Copa America": "conmebol-enabled",
  "FA Cup": "facup-enabled",
  "FIFA World Cup": "fifawc-enabled",
  "Leagues Cup": "leagues-enabled",
  "UEFA Europa Conference League": "uefaeuroconf-enabled",
  "UEFA European Championship": "uefaeuro-enabled",
  "UEFA Europa League": "uefaeuropa-enabled",
  "UEFA Women's Champions League": "uefawomenchampions-enabled",
};

export const SPORTS = {
  Bund: [
    { id: 6418, name: "1. FC Heidenheim 1846", pref: "bund-hdh" },
    { id: 131, name: "Bayer Leverkusen", pref: "bund-lev" },
    { id: 132, name: "Bayern Munich", pref: "bund-mun" },
    { id: 124, name: "Borussia Dortmund", pref: "bund-dor" },
    { id: 268, name: "Borussia Mönchengladbach", pref: "bund-mon" },
    { id: 125, name: "Eintracht Frankfurt", pref: "bund-einf" },
    { id: 3841, name: "FC Augsburg", pref: "bund-aug" },
    { id: 122, name: "FC Cologne", pref: "bund-col" },
    { id: 598, name: "1. FC Union Berlin", pref: "bund-fcub" },
    { id: 127, name: "Hamburg SV", pref: "bund-hsv" },
    { id: 2950, name: "Mainz", pref: "bund-main" },
    { id: 11420, name: "RB Leipzig", pref: "bund-lei" },
    { id: 126, name: "SC Freiburg", pref: "bund-frei" },
    { id: 270, name: "St. Pauli", pref: "bund-stp" },
    { id: 7911, name: "TSG Hoffenheim", pref: "bund-hof" },
    { id: 134, name: "VfB Stuttgart", pref: "bund-stu" },
    { id: 138, name: "VfL Wolfsburg", pref: "bund-wolf" },
    { id: 137, name: "Werder Bremen", pref: "bund-wer" },
  ],
  Bund2: [
    { id: 10382, name: "1. FC Magdeburg", pref: "bund2-fcm" },
    { id: 269, name: "1. FC Nürnberg", pref: "bund2-fcn" },
    { id: 2506, name: "Arminia Bielefeld", pref: "bund2-dsc" },
    { id: 7017, name: "Dynamo Dresden", pref: "bund2-sgd" },
    { id: 9707, name: "Fortuna Düsseldorf", pref: "bund2-f95" },
    { id: 2428, name: "Hannover 96", pref: "bund2-h96" },
    { id: 129, name: "Hertha Berlin", pref: "bund2-hert" },
    { id: 7884, name: "Holstein Kiel", pref: "bund2-kie" },
    { id: 130, name: "Kaiserslautern", pref: "bund2-fck" },
    { id: 4471, name: "Karlsruher SC", pref: "bund2-ksc" },
    { id: 9867, name: "Preußen Münster", pref: "bund2-prm" },
    { id: 3307, name: "SC Paderborn 07", pref: "bund2-scp" },
    { id: 10388, name: "SV 07 Elversberg", pref: "bund2-elv" },
    { id: 3812, name: "SV Darmstadt 98", pref: "bund2-svd" },
    { id: 133, name: "Schalke 04", pref: "bund2-scha" },
    { id: 3070, name: "SpVgg Greuther Fürth", pref: "bund2-spgf" },
    { id: 3067, name: "TSV Eintracht Braunschweig", pref: "bund2-ebs" },
    { id: 121, name: "VfL Bochum", pref: "bund2-boch" },
  ],
  UCL: [
    { id: 103, name: "AC Milan", pref: "ucl-mil" },
    { id: 174, name: "AS Monaco", pref: "ucl-monaco" },
    { id: 359, name: "Arsenal", pref: "ucl-ars" },
    { id: 362, name: "Aston Villa", pref: "ucl-avl" },
    { id: 105, name: "Atalanta", pref: "ucl-ata" },
    { id: 1068, name: "Atlético Madrid", pref: "ucl-atm" },
    { id: 83, name: "Barcelona", pref: "ucl-bar" },
    { id: 131, name: "Bayer Leverkusen", pref: "ucl-b04" },
    { id: 132, name: "Bayern Munich", pref: "ucl-mun" },
    { id: 1929, name: "Benfica", pref: "ucl-ben" },
    { id: 107, name: "Bologna", pref: "ucl-bol" },
    { id: 124, name: "Borussia Dortmund", pref: "ucl-dor" },
    { id: 6997, name: "Brest", pref: "ucl-bre" },
    { id: 256, name: "Celtic", pref: "ucl-cel" },
    { id: 570, name: "Club Brugge", pref: "ucl-brug" },
    { id: 597, name: "Dinamo Zagreb", pref: "ucl-dzg" },
    { id: 142, name: "Feyenoord Rotterdam", pref: "ucl-fey" },
    { id: 9812, name: "Girona", pref: "ucl-gir" },
    { id: 110, name: "Internazionale", pref: "ucl-int" },
    { id: 111, name: "Juventus", pref: "ucl-juv" },
    { id: 166, name: "Lille", pref: "ucl-lill" },
    { id: 364, name: "Liverpool", pref: "ucl-livs" },
    { id: 382, name: "Manchester City", pref: "ucl-mnc" },
    { id: 148, name: "PSV Eindhoven", pref: "ucl-psv" },
    { id: 160, name: "Paris Saint-Germain", pref: "ucl-psg" },
    { id: 11420, name: "RB Leipzig", pref: "ucl-rbl" },
    { id: 2790, name: "RB Salzburg", pref: "ucl-rbslz" },
    { id: 86, name: "Real Madrid", pref: "ucl-mad" },
    { id: 2290, name: "Red Star Belgrade", pref: "ucl-rsb" },
    { id: 3746, name: "SK Sturm Graz", pref: "ucl-stg" },
    { id: 493, name: "Shakhtar Donetsk", pref: "ucl-shk" },
    { id: 521, name: "Slovan Bratislava", pref: "ucl-slb" },
    { id: 433, name: "Sparta Prague", pref: "ucl-spp" },
    { id: 2250, name: "Sporting CP", pref: "ucl-scp" },
    { id: 134, name: "VfB Stuttgart", pref: "ucl-vfb" },
    { id: 2722, name: "Young Boys", pref: "ucl-yb" },
  ],
  "English League Championship": [
    { id: 392, name: "Birmingham City", pref: "elc-bir" },
    { id: 365, name: "Blackburn Rovers", pref: "elc-blk" },
    { id: 333, name: "Bristol City", pref: "elc-brc" },
    // { id: 379, name: "Burnley", pref: "elc-bur" },
    // { id: 347, name: "Cardiff City", pref: "elc-car" },
    { id: 372, name: "Charlton Athletic", pref: "elc-cha" },
    { id: 388, name: "Coventry City", pref: "elc-cov" },
    { id: 374, name: "Derby County", pref: "elc-der" },
    // { id: 335, name: "Huddersfield Town", pref: "elc-hud" },
    { id: 306, name: "Hull City", pref: "elc-hul" },
    { id: 373, name: "Ipswich Town", pref: "elc-ips" },
    // { id: 357, name: "Leeds United", pref: "elc-lee" },
    { id: 375, name: "Leicester City", pref: "elc-lei" },
    // { id: 301, name: "Luton Town", pref: "elc-ltn" },
    { id: 369, name: "Middlesbrough", pref: "elc-mid" },
    { id: 391, name: "Millwall", pref: "elc-mil" },
    { id: 381, name: "Norwich City", pref: "elc-nor" },
    { id: 311, name: "Oxford United", pref: "elc-oxf" },
    // { id: 307, name: "Plymouth Argyle", pref: "elc-ply" },
    { id: 385, name: "Portsmouth", pref: "elc-por" },
    { id: 394, name: "Preston North End", pref: "elc-pne" },
    { id: 334, name: "Queens Park Rangers", pref: "elc-qpr" },
    // { id: 402, name: "Rotherham United", pref: "elc-rot" },
    { id: 398, name: "Sheffield United", pref: "elc-shu" },
    { id: 399, name: "Sheffield Wednesday", pref: "elc-shw" },
    { id: 376, name: "Southampton", pref: "elc-sou" },
    { id: 336, name: "Stoke City", pref: "elc-stk" },
    // { id: 366, name: "Sunderland", pref: "elc-sun" },
    { id: 318, name: "Swansea City", pref: "elc-swa" },
    { id: 395, name: "Watford", pref: "elc-wat" },
    { id: 383, name: "West Bromwich Albion", pref: "elc-wba" },
    { id: 352, name: "Wrexham", pref: "elc-wxm" },
  ],
  "English League One": [
    { id: 3802, name: "AFC Wimbledon", pref: "l1-wim" },
    { id: 397, name: "Barnsley", pref: "l1-bar" },
    { id: 346, name: "Blackpool", pref: "l1-blp" },
    { id: 358, name: "Bolton Wanderers", pref: "l1-bol" },
    { id: 387, name: "Bradford City", pref: "l1-brd" },
    { id: 2567, name: "Burton Albion", pref: "l1-brt" },
    { id: 347, name: "Cardiff City", pref: "l1-car" },
    { id: 279, name: "Doncaster Rovers", pref: "l1-don" },
    { id: 324, name: "Exeter City", pref: "l1-exe" },
    { id: 335, name: "Huddersfield Town", pref: "l1-hud" },
    { id: 309, name: "Leyton Orient", pref: "l1-ley" },
    { id: 314, name: "Lincoln City", pref: "l1-lcn" },
    { id: 301, name: "Luton Town", pref: "l1-ltn" },
    { id: 304, name: "Mansfield Town", pref: "l1-mnf" },
    { id: 353, name: "Northampton Town", pref: "l1-nht" },
    { id: 342, name: "Peterborough United", pref: "l1-pet" },
    { id: 307, name: "Plymouth Argyle", pref: "l1-ply" },
    { id: 348, name: "Port Vale", pref: "l1-ptv" },
    { id: 338, name: "Reading", pref: "l1-rea" },
    { id: 402, name: "Rotherham United", pref: "l1-rot" },
    { id: 285, name: "Stevenage", pref: "l1-ste" },
    { id: 400, name: "Stockport County", pref: "l1-sto" },
    { id: 350, name: "Wigan Athletic", pref: "l1-wga" },
    { id: 344, name: "Wycombe Wanderers", pref: "l1-wyc" },
  ],
  EPL: [
    { id: 349, name: "AFC Bournemouth", pref: "epl-bou" },
    { id: 359, name: "Arsenal", pref: "epl-ars" },
    { id: 362, name: "Aston Villa", pref: "epl-avl" },
    { id: 337, name: "Brentford", pref: "epl-bre" },
    { id: 331, name: "Brighton & Hove Albion", pref: "epl-bha" },
    { id: 379, name: "Burnley", pref: "epl-bur" },
    { id: 363, name: "Chelsea", pref: "epl-che" },
    { id: 384, name: "Crystal Palace", pref: "epl-cry" },
    { id: 368, name: "Everton", pref: "epl-eve" },
    { id: 370, name: "Fulham", pref: "epl-ful" },
    { id: 357, name: "Leeds United", pref: "epl-lee" },
    { id: 364, name: "Liverpool", pref: "epl-liv" },
    { id: 382, name: "Manchester City", pref: "epl-mnc" },
    { id: 360, name: "Manchester United", pref: "epl-man" },
    { id: 361, name: "Newcastle United", pref: "epl-new" },
    { id: 393, name: "Nottingham Forest", pref: "epl-nfo" },
    { id: 366, name: "Sunderland", pref: "epl-sun" },
    { id: 367, name: "Tottenham Hotspur", pref: "epl-tot" },
    { id: 371, name: "West Ham United", pref: "epl-whu" },
    { id: 380, name: "Wolverhampton Wanderers", pref: "epl-wol" },
  ],
  ISR: [
    { id: 5218, name: "Beitar Jerusalem", pref: "isr-bje" },
    { id: 8329, name: "Bnei Sakhnin", pref: "isr-bsa" },
    { id: 13083, name: "Hapoel Be'er", pref: "isr-hbe" },
    { id: 19255, name: "Hapoel Hadera", pref: "isr-had" },
    { id: 9577, name: "Hapoel Haifa", pref: "isr-hah" },
    { id: 20970, name: "Hapoel Jerusalem", pref: "isr-hje" },
    { id: 8327, name: "Hapoel Kiryat Shmona", pref: "isr-hha" },
    { id: 22311, name: "Ironi Tiberias", pref: "isr-itb" },
    { id: 611, name: "Maccabi Haifa", pref: "isr-hai" },
    { id: 5945, name: "Maccabi Netanya", pref: "isr-net" },
    { id: 2983, name: "Maccabi Petah-Tikva", pref: "isr-mpt" },
    { id: 21517, name: "Maccabi Raina", pref: "isr-rai" },
    { id: 524, name: "Maccabi Tel-Aviv", pref: "isr-mta" },
    { id: 5269, name: "Moadon Sport Ashdod", pref: "isr-mos" },
  ],
  LaLiga: [
    { id: 96, name: "Alavés", pref: "laliga-alv" },
    { id: 93, name: "Athletic Club", pref: "laliga-ath" },
    { id: 1068, name: "Atlético Madrid", pref: "laliga-atl" },
    { id: 83, name: "Barcelona", pref: "laliga-bar" },
    { id: 85, name: "Celta Vigo", pref: "laliga-cel" },
    { id: 3751, name: "Elche", pref: "laliga-elc" },
    { id: 88, name: "Espanyol", pref: "laliga-esp" },
    { id: 2922, name: "Getafe", pref: "laliga-get" },
    { id: 9812, name: "Girona", pref: "laliga-gir" },
    { id: 1538, name: "Levante", pref: "laliga-lev" },
    { id: 84, name: "Mallorca", pref: "laliga-mll" },
    { id: 97, name: "Osasuna", pref: "laliga-osa" },
    { id: 101, name: "Rayo Vallecano", pref: "laliga-ray" },
    { id: 244, name: "Real Betis", pref: "laliga-bet" },
    { id: 86, name: "Real Madrid", pref: "laliga-mad" },
    { id: 92, name: "Real Oviedo", pref: "laliga-ovi" },
    { id: 89, name: "Real Sociedad", pref: "laliga-rso" },
    { id: 243, name: "Sevilla", pref: "laliga-sev" },
    { id: 94, name: "Valencia", pref: "laliga-val" },
    { id: 102, name: "Villarreal", pref: "laliga-vill" },
  ],
  LaLigaMX: [
    { id: 227, name: "América", pref: "lmx-ame" },
    { id: 223, name: "Atlas", pref: "lmx-atl" },
    { id: 234, name: "Atlético San Luis", pref: "lmx-asl" },
    { id: 218, name: "Cruz Azul", pref: "lmx-caz" },
    { id: 219, name: "Guadalajara", pref: "lmx-gdl" },
    { id: 229, name: "Juárez", pref: "lmx-jua" },
    { id: 222, name: "León", pref: "lmx-leo" },
    { id: 231, name: "Mazatlán", pref: "lmx-maz" },
    { id: 220, name: "Monterrey", pref: "lmx-mon" },
    { id: 221, name: "Necaxa", pref: "lmx-nec" },
    { id: 217, name: "Pachuca", pref: "lmx-pac" },
    { id: 230, name: "Puebla", pref: "lmx-pue" },
    { id: 228, name: "Querétaro", pref: "lmx-que" },
    { id: 225, name: "Santos Laguna", pref: "lmx-san" },
    { id: 226, name: "Tigres UANL", pref: "lmx-tig" },
    { id: 232, name: "Tijuana", pref: "lmx-tij" },
    { id: 224, name: "Toluca", pref: "lmx-tol" },
    { id: 233, name: "UNAM", pref: "lmx-una" },
  ],
  "Ligue 1": [
    { id: 172, name: "AJ Auxerre", pref: "ligue1-aux" },
    { id: 174, name: "AS Monaco", pref: "ligue1-mon" },
    { id: 7868, name: "Angers", pref: "ligue1-ang" },
    { id: 6997, name: "Brest", pref: "ligue1-bres" },
    { id: 3236, name: "Le Havre AC", pref: "ligue1-hac" },
    { id: 175, name: "Lens", pref: "ligue1-rcl" },
    { id: 166, name: "Lille", pref: "ligue1-lill" },
    { id: 273, name: "Lorient", pref: "ligue1-lor" },
    { id: 167, name: "Lyon", pref: "ligue1-lyon" },
    { id: 176, name: "Marseille", pref: "ligue1-mar" },
    { id: 177, name: "Metz", pref: "ligue1-metz" },
    { id: 165, name: "Nantes", pref: "ligue1-nant" },
    { id: 2502, name: "Nice", pref: "ligue1-nice" },
    { id: 6851, name: "Paris FC", pref: "ligue1-pfc" },
    { id: 160, name: "Paris Saint-Germain", pref: "ligue1-psg" },
    { id: 169, name: "Stade Rennais", pref: "ligue1-renn" },
    { id: 180, name: "Strasbourg", pref: "ligue1-stra" },
    { id: 179, name: "Toulouse", pref: "ligue1-tou" },
  ],
  MLS: [
    { id: 18418, name: "Atlanta United FC", pref: "mls-atl" },
    { id: 20906, name: "Austin FC", pref: "mls-atx" },
    { id: 9720, name: "CF Montréal", pref: "mls-mtl" },
    { id: 21300, name: "Charlotte FC", pref: "mls-clt" },
    { id: 182, name: "Chicago Fire FC", pref: "mls-chi" },
    { id: 184, name: "Colorado Rapids", pref: "mls-col" },
    { id: 183, name: "Columbus Crew", pref: "mls-clb" },
    { id: 193, name: "D.C. United", pref: "mls-dc" },
    { id: 18267, name: "FC Cincinnati", pref: "mls-cin" },
    { id: 185, name: "FC Dallas", pref: "mls-dal" },
    { id: 6077, name: "Houston Dynamo FC", pref: "mls-hou" },
    { id: 20232, name: "Inter Miami CF", pref: "mls-mia" },
    { id: 187, name: "LA Galaxy", pref: "mls-la" },
    { id: 18966, name: "LAFC", pref: "mls-lafc" },
    { id: 17362, name: "Minnesota United FC", pref: "mls-min" },
    { id: 18986, name: "Nashville SC", pref: "mls-nsh" },
    { id: 189, name: "New England Revolution", pref: "mls-ne" },
    { id: 17606, name: "New York City FC", pref: "mls-nyc" },
    { id: 190, name: "New York Red Bulls", pref: "mls-ny" },
    { id: 12011, name: "Orlando City SC", pref: "mls-orl" },
    { id: 10739, name: "Philadelphia Union", pref: "mls-phi" },
    { id: 9723, name: "Portland Timbers", pref: "mls-por" },
    { id: 4771, name: "Real Salt Lake", pref: "mls-rsl" },
    { id: 22529, name: "San Diego FC", pref: "mls-sd" },
    { id: 191, name: "San Jose Earthquakes", pref: "mls-sj" },
    { id: 9726, name: "Seattle Sounders FC", pref: "mls-sea" },
    { id: 186, name: "Sporting Kansas City", pref: "mls-skc" },
    { id: 21812, name: "St. Louis CITY SC", pref: "mls-stl" },
    { id: 7318, name: "Toronto FC", pref: "mls-tor" },
    { id: 9727, name: "Vancouver Whitecaps", pref: "mls-van" },
  ],
  "Serie A": [
    { id: 103, name: "AC Milan", pref: "seriea-mil" },
    { id: 104, name: "AS Roma", pref: "seriea-roma" },
    { id: 105, name: "Atalanta", pref: "seriea-ata" },
    { id: 107, name: "Bologna", pref: "seriea-bol" },
    { id: 2925, name: "Cagliari", pref: "seriea-cag" },
    { id: 2572, name: "Como", pref: "seriea-como" },
    { id: 4050, name: "Cremonese", pref: "seriea-cre" },
    { id: 109, name: "Fiorentina", pref: "seriea-fio" },
    { id: 3263, name: "Genoa", pref: "seriea-gen" },
    { id: 119, name: "Hellas Verona", pref: "seriea-ver" },
    { id: 110, name: "Internazionale", pref: "seriea-int" },
    { id: 111, name: "Juventus", pref: "seriea-juv" },
    { id: 112, name: "Lazio", pref: "seriea-laz" },
    { id: 113, name: "Lecce", pref: "seriea-lec" },
    { id: 114, name: "Napoli", pref: "seriea-nap" },
    { id: 115, name: "Parma", pref: "seriea-par" },
    { id: 3956, name: "Pisa", pref: "seriea-pis" },
    { id: 3997, name: "Sassuolo", pref: "seriea-sas" },
    { id: 239, name: "Torino", pref: "seriea-tor" },
    { id: 118, name: "Udinese", pref: "seriea-udn" },
  ],
};
